name: Create or Update Release
run-name: Create or update release for${{ github.event.release.tag_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Is this release a major, minor, or patch release? See https://semver.org for definitions.'
        required: true
        default: 'minor'
        type: choice
        options:
            - major
            - minor
            - patch
#      commit_sha:
#        description: 'Commit SHA to cherry-pick (only required for patch)'
#        required: false
#        type: string
#      release_version:
#        description: 'Release version (only required for non-patch)'
#        default: 'v1.0.0'
#        required: false
#        type: string

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          if [[ "${{ github.event.inputs.release_type }}" != "patch" && "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Error: Can only create/update release from the main branch for non-patch releases"
            exit 1
          elif [[ "${{ github.event.inputs.release_type }}" == "patch" && ! "${{ github.ref }}" =~ ^refs/heads/release/ ]]; then
            echo "Error: Can only create patch releases from existing release/* branches"
            exit 1
          fi

  bump-version:
    needs: validate-source-branch
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.increment-version.outputs.new_version }}
    steps:
      - name: Checkout the branch the workflow is run from
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: false

      - name: Authenticate with github
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version
        id: increment-version
        run: |
          version=$(git tag --sort=creatordate | tail -1)
          IFS='.' read -r major minor patch <<< "${version:1}"
          if [[ "${{ github.event.inputs.release_type }}" == "major" ]]; then
            major=$((major + 1))
            minor=0
            patch=0
          elif [[ "${{ github.event.inputs.release_type }}" == "minor" ]]; then
            minor=$((minor + 1))
            patch=0
          elif [[ "${{ github.event.inputs.release_type }}" == "patch" ]]; then
            patch=$((patch + 1))
          else
            echo "Error: Unknown release type ${{ github.event.inputs.release_type }}"
            exit 1
          fi
          new_version="v${major}.${minor}.${patch}"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "Bump version $version ---> $new_version"


  create-release:
    needs: bump-version
    if: ${{ github.event.inputs.release_type != 'patch' }}
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout the branch the workflow is run from
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Authenticate with github
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        run: |
          git checkout -b release/$RELEASE_VERSION
          git tag $RELEASE_VERSION
          git push origin release/$RELEASE_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ needs.bump-version.outputs.new_version }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.bump-version.outputs.new_version }}
          release_name: Release ${{ needs.bump-version.outputs.new_version }}
          body: |
            Release ${{ github.event.inputs.release_type }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-release:
    needs: bump-version
    if: ${{ github.event.inputs.release_type == 'patch' }}
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout the branch the workflow is run from
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Authenticate with github
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update release branch with patch
        run: |
          git fetch origin main
          git cherry-pick origin/main ${{ github.event.inputs.commit_sha }}
          git push origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.bump-version.outputs.new_version }}
          release_name: Release ${{ needs.bump-version.outputs.new_version }}
          body: |
            Release ${{ github.event.inputs.release_type }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}