name: Deploy to prod
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Is this release a major, minor, or patch release? See https://semver.org for definitions.'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
#      version:
#        description: 'This will be used to tag the release'
#        required: true
#        default: 'v0.0.0'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  prepare-release-job:
    uses: ./.github/workflows/prepare_release.yaml
    with:
      env: 'prod'
      release_type: ${{ inputs.release_type }}

  deploy-job:
    uses: ./.github/workflows/deploy_to_env.yaml
    with:
      env: 'prod'
      release_version: ${{ jobs.prepare-release-job.outputs.release_version }}
      release_branch: ${{ jobs.prepare-release-job.outputs.release_branch }}
