name: Deploy to prod
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Is this release a major, minor, or patch release? See https://semver.org for definitions.'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  prepare-release-job:
    uses: ./.github/workflows/prepare_release.yaml
    with:
      release_type: ${{ inputs.release_type }}

  deploy-job:
    uses: ./.github/workflows/deploy_to_env.yaml
    needs: [prepare-release-job]
    with:
      env: 'prod'
      release_version: ${{ needs.prepare-release-job.outputs.release_version }}
      release_branch: ${{ needs.prepare-release-job.outputs.release_branch }}
      release_type: ${{ inputs.release_type }}
      cleanup_failed_deployment: true

  rollback-job:
    needs: [deploy-job]
    if: |
      always() &&
      needs.deploy-job.result == 'failure'
    uses: ./.github/workflows/deploy_to_env.yaml
    with:
      env: 'prod'
      release_branch: ${{ github.ref }}
      cleanup_failed_deployment: false
