name: Deploy to dev
on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  deploy-job:
    uses: ./.github/workflows/deploy_to_env.yaml
    with:
      env: 'dev'
      release_branch: ${{ github.ref }}
      run_check_only: false
