name: Deploy to selected environment

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Which environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - major
          - minor
      version:
        description: 'The version that will be deployed'
        required: true
        default: 'v0.0.0'
        type: string
      delete_release_branch_on_failure:
        description: 'Whether to delete release branch if deployment fails'
        required: true
        default: true
        type: boolean
      manual_call:
        description: 'To distinguish workflow_call from workflow_dispatch'
        type: boolean
        required: false
        default: true
  workflow_call:
    inputs:
      env:
        description: 'Which environment to deploy to'
        required: true
        default: 'dev'
        type: string
      version:
        description: 'The version that will be deployed'
        required: true
        default: 'v0.0.0'
        type: string
      delete_release_branch_on_failure:
        description: 'Whether to delete release branch if deployment fails'
        required: true
        default: true
        type: boolean
      manual_call:
        description: 'To distinguish workflow_call from workflow_dispatch'
        type: boolean
        required: false
        default: false

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          if ${{ inputs.manual_call }} && [[ "${{ inputs.env }}" == "prod" && "${{ github.ref }}" != refs/heads/release/* ]]; then
            echo "Error: Can only deploy from existing release/* branches in production"
            exit 1
          fi

  deploy:
    needs: [ validate-source-branch ]
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
    env:
      RELEASE_VERSION: ${{ inputs.version }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_BRANCH: release/${{ inputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: $RELEASE_BRANCH

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: $RELEASE_VERSION
          release_name: Release $RELEASE_VERSION
          body: |
            Release $$RELEASE_VERSION
          draft: false
          prerelease: false

      - name: Deploy to production
        run: echo "Deploying to ${{ inputs.env }} ..."

  cleanup-failed-deployment:
    needs: [ deploy ]
    runs-on: ubuntu-latest
    if: failure()
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_VERSION: ${{ inputs.version }}
      RELEASE_BRANCH: release/${{ inputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Delete GitHub release
        continue-on-error: true
        run: |
          release_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/$RELEASE_VERSION \
            | jq -r '.id')
          if [ "$release_id" != "null" ]; then
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/releases/$release_id
            echo "Release $RELEASE_VERSION deleted."
          else
            echo "Release $RELEASE_VERSION not found."
          fi
      - name: Delete Git tag
        continue-on-error: true
        run: |
          echo "Release version: $RELEASE_VERSION"
          git push --delete origin $RELEASE_VERSION

      - name: Delete release branch
        if: ${{ inputs.delete_release_branch_on_failure }}
        continue-on-error: true
        run: |
          git push origin --delete $RELEASE_BRANCH